# Generated by Django 4.0.4 on 2022-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
